dimensions:
  time: 
    size: 1104
    limited: False
    day_step: 8
    years: 24
  lat: 
    size: 1544
    limited: True
  lon: 
    size: 1592
    limited: True
  layer:
    size: 20
    limited: True
  croptype:
    size: 2
    limited: True
  vegtype:
    size: 15
    limited: True
    #selection:
    #  NET:
    #    - 1
    #    - 2
    #  BDT:
    #    - 7
    #    - 8
    #  GRA:
    #    - 12
    #    - 13
    #    - 14
    #  CRO:
    #    - 15
    #    - 16


paths:
  coords: /p/data1/jibg31/poppe1/EDWUE/EDWUE/8daily/
  grid: /p/data1/jibg31/CLM5_EU3_eLTER/outputs/006/join_8daily/
  pft: /p/data1/jibg31/CLM5_EU3_eLTER/outputs/006/join_8daily/pft/
  forcings: /p/data1/jibg31/poppe1/HOLIDROUGHT/variables/
  surface: /p/scratch/cjibg31/jibg3105/CESMDataRoot/InputData/lnd/clm2/surfdata_map/surfdata_CLM5EU3_v4_pos.nc

variables:
  coords:
    - latitude
    - longitude
  grid:
    - GPP
    - QFLX_EVAP_TOT
    - QFLX_EVAP_VEG
    - TLAI
    - TOTVEGC
    - TOTSOMC
    - H2OSOI
  forcings:
    - VPD
    - P
  surface:
    - PCT_CROP
    - PCT_NATVEG
    - PCT_CFT
    - PCT_NAT_PFT
  pft:
    - GPP
    - Tr
    - ET

variable_names:
  GPP: GPP
  QFLX_EVAP_TOT: ET
  QFLX_EVAP_VEG: Tr
  P: Precip
  VPD: VPD
  TLAI: LAI
  H2OSOI: SM
  latitude: latitude
  longitude: longitude
  time: time

variable_factor:
  GPP: 86400
  ET: 86400
  Tr: 86400

variable_dtype: 
  GPP: float32
  ET: float32
  Tr: float32
  Precip: float32
  VPD: float32
  LAI: float32
  H2OSOI: float32
  TOTVEGC: float32
  TOTSOMC: float32
  PCT_CFT: float32
  PCT_NAT_PFT: float32
  PCT_CROP: float32
  PCT_NATVEG: float32
  latitude: float32
  longitude: float32

variable_dimensions:
  GPP:
    - time
    - lat
    - lon
  ET: 
    - time
    - lat
    - lon
  Tr:
    - time
    - lat
    - lon
  Precip: 
    - time
    - lat
    - lon
  VPD:
    - time
    - lat
    - lon
  LAI:
    - time
    - lat
    - lon
  SM:
    - time
    - layer
    - lat
    - lon
  TOTVEGC:
    - time
    - lat
    - lon
  TOTSOMC:
    - time
    - lat
    - lon
  PCT_CROP:
    - lat
    - lon
  PCT_NATVEG:
    - lat
    - lon
  PCT_CFT:
    - croptype
    - lat
    - lon
  PCT_NAT_PFT:
    - vegtype
    - lat
    - lon
  latitude:
    - lat
    - lon
  longitude:
    - lat
    - lon
  time: 
    - time



variable_attributes:
  latitude:
    units: degrees_north
    standard_name: latitude
    long_name: Latitude
  longitude:
    units: degrees_east
    standard_name: longitude
    long_name: Longitude
  time:
    calendar: standard
    units: days since 1995-01-01
    standard_name: time
    timestamp_label_side: left
  GPP:
    units: gC m-2 day-1
    standard_name: gross_primary_productivity
    long_name: Gross Primary Productivity
    source: land surface model
  ET:
    units: mm m-2 day-1
    standard_name: evapotranspiration
    long_name: Evapotranspiration
    source: land surface model
  Tr:
    units: mm m-2 day-1
    standard_name: transpiration
    long_name: Transpiration
    source: land surface model
  LAI:
    units: m2 m-2
    standard_name: leaf_area_index
    long_name: Leaf Area Index
    source: land surface model
  TOTVEGC:
    units: gC m-2
    standard_name: total_vegetation_carbon
    long_name: Total Vegetation Carbon
    source: land surface model
  TOTSOMC:
    units: gC m-2
    standard_name: total_soil_organic_carbon
    long_name: Total Soil Organic Carbon
    source: land surface model
  SM:
    units: m3 m-3
    standard_name: soil_moisture
    long_name: Soil Moisture
    source: land surface model
  VPD:
    units: kPa
    standard_name: vapor_pressure_deficit
    long_name: Vapor Pressure Deficit
    source: atmospheric model
  Precip:
    units: mm day-1
    standard_name: precipitation
    long_name: Precipitation
    source: atmospheric model
  EWUE:
    units: gC mm-1 
    standard_name: ecosystem_water_use_efficiency
    long_name: Ecosystem Water Use Efficiency
    calculation: GPP / ET
  TWUE:
    units: gC mm-1
    standard_name: transpiration_water_use_efficiency
    long_name: Transpiration Water Use Efficiency
    calculation: GPP / Tr
  IWUE:
    units: gC kPa mm-1
    standard_name: inherent_water_use_efficiency
    long_name: Inherent Water Use Efficiency
    calculation: GPP * (Tr/VPD)

global_attributes:
  conventions: CF-1.8
  conventions_url: http://www.cfconventions.org
  licence: FZJ European 3km Community Land Model v5 - Biogeochemical Mode; Water-Use Efficiency Dataset (c) 2025 by Christian Poppe Terán, Alexandre Belleflamme, Bibi S. Naz, Harrie-Jan Hendricks-Franssen, and Harry Vereecken of Forschungszentrum Jülich (Germany) is licensed under Creative Commons Attribution 4.0 International. To view a copy of this license, visit https://creativecommons.org/licenses/by/4.0/
  licence_url: https://creativecommons.org/licenses/by/4.0/deed.en
  experiment: CLM5_BGC_EU3_eLTER_006
  land_surface_model: Community Land Movel v5 
  land_surface_model_version: release-clm5.0.34-24-gdc5ea974
  surface_dataset: surfdata_CLM5EU3_FATES_east[west]_v3.nc
  pft:  "Bare ground, NET Temperate, NET Boreal, NDT Boreal, BET Tropical, BET Temperate, BDT tropical, BDT temperate, BDT boreal, BES temperate, BDS temperate, BDS boreal, C3 grass arctic, C3 grass, C4 grass"
  pft_abbreviations: "NET: Needleleaf Evergreen Tree; NDT: Needleleaf Deciduous Tree; BET: Broadleaf Evergreen Tree; BDT: Broadleaf Deciduous Tree; BES: Broadleaf Evergreen Shrub; BDS: Broadleaf Deciduous Shrub"
  layer_depths: "0.010, 0.040, 0.090, 0.160, 0.260, 0.400, 0.580, 0.800, 1.060, 1.360, 1.700, 2.080, 2.500, 2.990, 3.580, 4.270, 5.060, 5.950, 6.940, 8.030]"
  atmospheric_data: COSMOREA6
  atmospheric_data_link: https://reanalysis.meteo.uni-bonn.de/?COSMO-REA6
  atmospheric_postprocessing: remapped via ESMF_regrid_with_weights, first-order conservative
  postprocessing: resampled to 8-daily means and transformed to [per day] units
  project: eLTER PLUS
  domain: CORDEX-EU
  DOI: ""
  created by: Christian Poppe Terán
  citation: Poppe Terán, Christian; Belleflamme, Alexandre; Naz S., Bibi; Hendricks-Franssen, Harrie-Jan; Vereecken, Harry; 2025, "European 3km CLM5-BGC Water-Use Efficiency Dataset", https://doi.org/10.26165/JUELICH-DATA/GROHKP, Jülich DATA, V1
  title: European 3km CLM5-BGC Water-Use Efficiency Dataset
  comment: "Land surface model simulation performed by Research Centre Juelich, Institute of Bio- and Geosciences (IBG-3); simulation and processing: Christian Poppe Terán c.poppe@fz-juelich.de (ORCID=0000-0003-2283-0462), Alexandre Belleflamme, Bibi S. Naz, Harrie-Jan Hendricks-Franssen, Harry Vereecken"
  date: "2025-08-27"
  version: 1.0
  institution: Institute of Bio and Geosciences - Agrosphere (IBG-3), Research Centre Jülich
  contact: c.poppe@fz-juelich.de
  acknowledgments: This project has received funding from the European Union's Horizon 2020 research and innovation programme under grant agreement No 871128 (eLTER PLUS). The creator gratefully acknowledges the computing time granted through JARA on the supercomputer JURECA at Research Centre Jülich.



